import {token,reconcile,isKanji,worksheet,hira,layout} from './core.mjs';
import {worksheetPdf} from './pdf.mjs';
const $=id=>document.getElementById(id);
const examples=[['水を飲む',{水:'みず',飲:'の'}],['写真を写す',{写:'しゃ',真:'しん'}],['礼をする',{礼:'れい'}],['区に分ける',{区:'く',分:'わ'}],['学校に行く',{学:'がっ',校:'こう',行:'い'}],['青い空',{青:'あお',空:'そら'}],['元気に走る',{元:'げん',気:'き',走:'はし'}],['本を読む',{本:'ほん',読:'よ'}],['花を見つける',{花:'はな',見:'み'}],['雨がふる',{雨:'あめ'}]];
// Each example has its own reading, so identical characters may have different readings.
const state={unitName:'',printUnit:true,grade:'',marker:'',printMeta:true,upper:5,lower:5,rows:2,guides:true,divider:false,numberVisible:Array(30).fill(true),questions:Array.from({length:30},()=>[])};
examples.forEach(([text,readings],i)=>state.questions[i<5?i:15+i-5]=[...text].map(c=>token(c,readings[c]||'')));
// 写真を写す uses different readings for the two occurrences of 写.
state.questions[1][3].reading='うつ';
let half=0,selected={question:0,char:0};
let pdfUrl;
function preview(){if(pdfUrl){URL.revokeObjectURL(pdfUrl);pdfUrl=null;$('pdfResult').replaceChildren()}const result=worksheet(state);$('paper').innerHTML=result.svg;$('metrics').textContent=`${result.count}問 ／ 升目 約${result.box.toFixed(1)}mm ／ ${result.single?'１段':'２段'}`;
const visible=[...state.questions.slice(0,state.upper),...state.questions.slice(15,15+result.shownLower)].flat();let missing=visible.filter(t=>(t.mode==='blank'||t.mode==='kana')&&isKanji(t.char)&&!t.reading).length;
const notice=result.single&&state.lower>0?'一段を選んでいるため、下半分は印刷しません。入力内容は保持しています。 ':''; $('status').textContent=notice+(missing?`読みが未入力の文字が${missing}個あります。文字を選んで、読みを入力してください。`:result.box<8?'問題数や文の長さによって、升目が小さくなっています。配置を確認してください。':'');$('bottomTab').textContent=state.lower===0?'下半分（なし）':result.single?'下半分（印刷対象外）':'下半分';$('bottomTab').disabled=state.lower===0;}
function el(tag,text,cls){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e}
function renderQuestions(){const container=$('questions');container.replaceChildren();let count=half?state.lower:state.upper;for(let i=0;i<count;i++){const idx=(half?15:0)+i,q=state.questions[idx];const card=el('div',undefined,'question');const head=el('div',undefined,'qhead');const number=i+1+(half?state.upper:0),numberButton=el('button',`${number} 番号：${state.numberVisible[idx]?'表示':'非表示'}`,'number-toggle');numberButton.setAttribute('aria-label',`問題${number}の番号表示を切り替え`);numberButton.setAttribute('aria-pressed',String(state.numberVisible[idx]));numberButton.onclick=()=>{state.numberVisible[idx]=!state.numberVisible[idx];numberButton.textContent=`${number} 番号：${state.numberVisible[idx]?'表示':'非表示'}`;numberButton.setAttribute('aria-pressed',String(state.numberVisible[idx]));preview()};head.append(numberButton);const inp=el('input');inp.value=q.map(t=>t.char).join('');inp.maxLength=40;inp.placeholder='単語や短い文を入力';inp.setAttribute('aria-label',`問題${i+1+(half?state.upper:0)}`);head.append(inp);card.append(head);const body=el('div');card.append(body);container.append(card);
const renderBody=()=>{body.replaceChildren();const chips=el('div',undefined,'chips');state.questions[idx].forEach((t,j)=>{const b=el('button',t.char,`chip ${t.mode} ${selected.question===idx&&selected.char===j?'active':''}`);b.setAttribute('aria-label',`${t.char}：${{blank:'空欄升',kana:'ひらがな',text:'そのまま'}[t.mode]}`);b.onclick=()=>{selected={question:idx,char:j};renderQuestions()};chips.append(b)});body.append(chips);if(selected.question===idx&&state.questions[idx][selected.char]){const t=state.questions[idx][selected.char],edit=el('div',undefined,'editbox');edit.append(el('strong',`「${t.char}」の表示`));const modes=el('div',undefined,'modes');for(const [mode,label]of [['text','そのまま'],['kana','ひらがな'],['blank','空欄升']]){const b=el('button',label,t.mode===mode?'active':'');b.onclick=()=>{t.mode=mode;preview();renderBody()};modes.append(b)}edit.append(modes);const label=el('label','読み・ふりがな（編集できます）');const read=el('input');read.value=t.reading;read.placeholder='例：がく';read.setAttribute('aria-label',`${t.char}の読み`);read.maxLength=20;read.oninput=()=>{t.reading=hira(read.value);preview()};label.append(read);edit.append(label);edit.append(el('p','空欄升では右側に表示。ひらがなでは、この読みに置き換えます。','helper'));body.append(edit)}};
inp.addEventListener('input',()=>{state.questions[idx]=reconcile(inp.value,state.questions[idx]);if(selected.question===idx&&selected.char>=state.questions[idx].length)selected.char=Math.max(0,state.questions[idx].length-1);renderBody();preview()});renderBody()}}
for(const key of ['unitName','grade','marker'])$(key).oninput=()=>{state[key]=$(key).value;preview()};for(const key of ['upper','lower']){$(key).onchange=()=>{const min=key==='upper'?1:0,v=Math.trunc(Number($(key).value));state[key]=Math.max(min,Math.min(15,Number.isFinite(v)?v:5));$(key).value=state[key];state.rows=state.upper>=10||state.lower>0?2:1;$('oneRow').checked=state.rows===1;$('twoRows').checked=state.rows===2;if(key==='lower'&&state.lower===0&&half)tab(0);renderQuestions();preview()}}for(const key of ['guides','divider','printUnit','printMeta'])$(key).onchange=()=>{state[key]=$(key).checked;preview()};
for(const [id,rows] of [['oneRow',1],['twoRows',2]])$(id).onchange=()=>{state.rows=rows;$('oneRow').checked=rows===1;$('twoRows').checked=rows===2;preview()};
function tab(h){half=h;selected={question:h?15:0,char:0};$('topTab').classList.toggle('active',!h);$('bottomTab').classList.toggle('active',!!h);$('topTab').setAttribute('aria-selected',String(!h));$('bottomTab').setAttribute('aria-selected',String(!!h));renderQuestions()}
$('topTab').onclick=()=>tab(0);$('bottomTab').onclick=()=>tab(1);$('print').onclick=()=>window.print();renderQuestions();preview();
if(document.modelContext?.registerTool){try{document.modelContext.registerTool({name:'read_worksheet',description:'Read the current worksheet questions, character display modes, readings and A4 cell size.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({unitName:state.unitName,printUnit:state.printUnit,grade:state.grade,marker:state.marker,printMeta:state.printMeta,upper:state.upper,lower:state.lower,numberVisible:state.numberVisible,questions:[...state.questions.slice(0,state.upper),...state.questions.slice(15,15+state.lower)],box:worksheet(state).box})})}catch(e){console.warn('Tool registration unavailable')}}

$('pdf').onclick=async()=>{
 const button=$('pdf');button.disabled=true;button.textContent='PDFを作っています…';
 try{const blob=await worksheetPdf(worksheet(state).svg);if(pdfUrl)URL.revokeObjectURL(pdfUrl);pdfUrl=URL.createObjectURL(blob);
 const link=el('a','PDFを開く');link.href=pdfUrl;link.target='_blank';link.rel='noopener';
 const note=el('p','「PDFを開く」を押し、iPadの共有メニューから「プリント」を選んでください。PDFを保存してから開くこともできます。');
 const save=el('a','PDFを保存');save.href=pdfUrl;save.download='kanji-print.pdf';save.style.marginLeft='8px';
 $('pdfResult').replaceChildren(link,save,note);$('pdfResult').scrollIntoView({block:'nearest'});
 }catch(e){$('pdfResult').textContent='PDFを作れませんでした。Safariでこのページを開き、もう一度お試しください。';console.error(e)}
 finally{button.disabled=false;button.textContent='PDFを作る（iPad用）'}
};
